mod_id=middle_earth
mod_name=Middle-earth
mod_license=ARR
mod_version=1.0.1-1.21.1-beta
maven_group=net.sevenstars.middleearth
archives_base_name=Middle-earth
mod_authors=Jukoz, ObliviousCrab, TomSchlom, Boenndal, Jooble, Sindavar, Angmarzku, Scosher, Osserc, Kolhosp, CoffeeViking, Nautilus, Arwaeneth, Thud, Akkon, Louise
mod_description=Join the legendary world of Tolkien's universe from The Lord of The Rings to the Hobbit and more!
