org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.daemon=false
systemProp.org.gradle.internal.http.socketTimeout=120000
systemProp.org.gradle.internal.http.connectionTimeout=120000
systemProp.java.net.preferIPv4Stack=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.244
neo_version_range=[21.1.233,21.2)
loader_version_range=[4,)
