pluginManagement {
    repositories {
        maven {
            name = 'NeoForged'
            url = 'https://maven.neoforged.net/releases'
            content {
                includeGroupByRegex 'net\\.neoforged.*'
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id 'net.neoforged.moddev.repositories' version '1.0.17'
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        maven {
            name = 'TerraformersMC'
            url = 'https://maven.terraformersmc.com/'
        }
        maven {
            name = 'Shedaniel'
            url = 'https://maven.shedaniel.me'
        }
        maven {
            name = 'ModMaven'
            url = 'https://modmaven.dev'
        }
        maven {
            url = 'https://api.modrinth.com/maven'
        }
    }
}

rootProject.name = 'sevenstars-project'
include 'sevenstars-api', 'of-beasts-and-wild-things', 'middle-earth'
