modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Campione01/middle-earth/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://modrinth.com/mod/middle-earth"
logoFile="assets/middle-earth/icon.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="middle-earth.mixins.json"

[[mixins]]
config="middle-earth-sable.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="sevenstars_api"
type="required"
versionRange="[${mod_version}]"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="wild_things"
type="required"
versionRange="[${mod_version}]"
ordering="AFTER"
side="BOTH"
