package net.sevenstars.middleearth.world.biomes;

import net.sevenstars.middleearth.MiddleEarth;
import net.minecraft.registry.RegistryKey;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.util.Identifier;
import net.minecraft.world.biome.Biome;
import net.minecraft.world.biome.BiomeKeys;
import net.sevenstars.middleearth.datageneration.content.TranslationEntries;
import net.sevenstars.middleearth.registries.content.biomevents.BiomeEventRegistryUtil;

public class BiomeKeyRegistryME extends BiomeKeys {
    // region SURFACE
    public static final RegistryKey<Biome> ANDUIN_VALES = register("anduin_vales");
    public static final RegistryKey<Biome> ANDUIN_VALES_FOREST = register("anduin_vales_forest");
    public static final RegistryKey<Biome> ANORIEN = register("anorien");
    public static final RegistryKey<Biome> ANORIEN_RIVERSIDE = register("anorien_riverside");
    public static final RegistryKey<Biome> ANORIEN_FOOTHILLS = register("anorien_foothills");
    public static final RegistryKey<Biome> BARROW_DOWNS = register("barrow_downs");
    public static final RegistryKey<Biome> BELERIAND_ISLAND = register("beleriand_island");
    public static final RegistryKey<Biome> BELFALAS = register("belfalas");
    public static final RegistryKey<Biome> BELFALAS_FOREST = register("belfalas_forest");
    public static final RegistryKey<Biome> BELFALAS_HILLS = register("belfalas_hills");
    public static final RegistryKey<Biome> BELFALAS_BEACH = register("belfalas_beach");
    public static final RegistryKey<Biome> BLACKROOT_VALE = register("blackroot_vale");
    public static final RegistryKey<Biome> BLACKROOT_FOREST = register("blackroot_forest");
    public static final RegistryKey<Biome> BLUE_MOUNTAINS_FOOTHILLS = register("blue_mountains_foothills");
    public static final RegistryKey<Biome> BLUE_MOUNTAINS_BASE = register("blue_mountains_base");
    public static final RegistryKey<Biome> BLUE_MOUNTAINS = register("blue_mountains");
    public static final RegistryKey<Biome> BLUE_MOUNTAINS_HIGH_LANDS = register("blue_mountains_high_lands");
    public static final RegistryKey<Biome> BLUE_MOUNTAINS_PEAKS = register("blue_mountains_peaks");
    public static final RegistryKey<Biome> BLUE_MOUNTAINS_WOODS = register("blue_mountains_woods");
    public static final RegistryKey<Biome> BROWN_LANDS = register("brown_lands");
    public static final RegistryKey<Biome> CARADHRAS_BASE = register("caradhras_base");
    public static final RegistryKey<Biome> CARADHRAS = register("caradhras");
    public static final RegistryKey<Biome> CARADHRAS_PEAKS = register("caradhras_peaks");
    public static final RegistryKey<Biome> CELEBDIL_BASE = register("celebdil_base");
    public static final RegistryKey<Biome> CELEBDIL = register("celebdil");
    public static final RegistryKey<Biome> CELEBDIL_PEAKS = register("celebdil_peaks");
    public static final RegistryKey<Biome> CORSAIR_COASTS = register("corsair_coasts");
    public static final RegistryKey<Biome> DALE = register("dale");
    public static final RegistryKey<Biome> DALE_FOREST = register("dale_forest");
    public static final RegistryKey<Biome> DALE_MEADOW = register("dale_meadow");
    public static final RegistryKey<Biome> DALE_CITY = register("dale_city");
    public static final RegistryKey<Biome> DAGORLAD = register("dagorlad");
    public static final RegistryKey<Biome> DARK_MIRKWOOD = register("dark_mirkwood");
    public static final RegistryKey<Biome> DARK_MIRKWOOD_EDGE = register("dark_mirkwood_edge");
    public static final RegistryKey<Biome> DARK_ANDUIN_VALES = register("dark_anduin_vales");
    public static final RegistryKey<Biome> DEAD_MARSHES = register("dead_marshes");
    public static final RegistryKey<Biome> DEAD_MARSHES_WATER = register("dead_marshes_water");
    public static final RegistryKey<Biome> DESOLATED_LANDS = register("desolated_lands");
    public static final RegistryKey<Biome> DOL_GULDUR = register("dol_guldur");
    public static final RegistryKey<Biome> DOL_GULDUR_HILL = register("dol_guldur_hill");
    public static final RegistryKey<Biome> DORWINION = register("dorwinion");
    public static final RegistryKey<Biome> DORWINION_LAVENDER_FIELD = register("dorwinion_lavender_field");
    public static final RegistryKey<Biome> DORWINION_HILLS = register("dorwinion_hills");
    public static final RegistryKey<Biome> DRUWAITH_IAUR = register("druwaith_iaur");
    public static final RegistryKey<Biome> DUNLAND = register("dunland");
    public static final RegistryKey<Biome> DUNLAND_FOOTHILLS = register("dunland_foothills");
    public static final RegistryKey<Biome> DUNLAND_HILLS = register("dunland_hills");
    public static final RegistryKey<Biome> EAST_BIGHT = register("east_bight");
    public static final RegistryKey<Biome> EASTERN_NURN = register("eastern_nurn");
    public static final RegistryKey<Biome> EASTERN_RHOVANION = register("eastern_rhovanion");
    public static final RegistryKey<Biome> EASTERN_RHOVANION_FOREST = register("eastern_rhovanion_forest");
    public static final RegistryKey<Biome> EMYN_MUIL = register("emyn_muil");
    public static final RegistryKey<Biome> EMYN_MUIL_CLIFFS = register("emyn_muil_cliffs");
    public static final RegistryKey<Biome> EMYN_MUIL_PEAKS = register("emyn_muil_peaks");
    public static final RegistryKey<Biome> EMYN_MUIL_POND = register("emyn_muil_pond");
    public static final RegistryKey<Biome> ENEDWAITH = register("enedwaith");
    public static final RegistryKey<Biome> ENEDWAITH_FIELD = register("enedwaith_field");
    public static final RegistryKey<Biome> ENEDWAITH_WHEAT_FIELD = register("enedwaith_wheat_field");
    public static final RegistryKey<Biome> EPHEL_DUATH = register("ephel_duath");
    public static final RegistryKey<Biome> EPHEL_DUATH_BASE = register("ephel_duath_base");
    public static final RegistryKey<Biome> EPHEL_DUATH_PEAKS = register("ephel_duath_peaks");
    public static final RegistryKey<Biome> ERED_LITHUI = register("ered_lithui");
    public static final RegistryKey<Biome> ERED_LITHUI_BASE = register("ered_lithui_base");
    public static final RegistryKey<Biome> ERED_LITHUI_PEAKS = register("ered_lithui_peaks");
    public static final RegistryKey<Biome> EREGION = register("eregion");
    public static final RegistryKey<Biome> EREGION_FOREST = register("eregion_forest");
    public static final RegistryKey<Biome> EREGION_GLADE = register("eregion_glade");
    public static final RegistryKey<Biome> ETHIR_ANDUIN = register("ethir_anduin");
    public static final RegistryKey<Biome> ETHIR_ANDUIN_RIVER_DELTA = register("ethir_anduin_river_delta");
    public static final RegistryKey<Biome> FANGORN = register("fangorn");
    public static final RegistryKey<Biome> FANGORN_FOOTHILLS = register("fangorn_foothills");
    public static final RegistryKey<Biome> FANUIDHOL_BASE = register("fanuidhol_base");
    public static final RegistryKey<Biome> FANUIDHOL = register("fanuidhol");
    public static final RegistryKey<Biome> FANUIDHOL_PEAKS = register("fanuidhol_peaks");
    public static final RegistryKey<Biome> MIRKWOOD_RIVER = register("mirkwood_river");
    public static final RegistryKey<Biome> FORODWAITH = register("forodwaith");
    public static final RegistryKey<Biome> FROZEN_OCEAN = register("frozen_ocean");
    public static final RegistryKey<Biome> FROZEN_POND = register("frozen_pond");
    public static final RegistryKey<Biome> LINDON_SHORES = register("lindon_shores");
    public static final RegistryKey<Biome> LINDON_SHORES_CLIFFS = register("lindon_shores_cliffs");
    public static final RegistryKey<Biome> GONDOR = register("gondor");
    public static final RegistryKey<Biome> GONDOR_FOREST = register("gondor_forest");
    public static final RegistryKey<Biome> GONDOR_HILL = register("gondor_hill");
    public static final RegistryKey<Biome> GORGOROTH = register("gorgoroth");
    public static final RegistryKey<Biome> GORGOROTH_ASHEN_WOODS = register("gorgoroth_ashen_woods");
    public static final RegistryKey<Biome> GORGOROTH_DELTA = register("gorgoroth_delta");
    public static final RegistryKey<Biome> GREY_MOUNTAINS = register("grey_mountains");
    public static final RegistryKey<Biome> GREY_MOUNTAINS_BASE = register("grey_mountains_base");
    public static final RegistryKey<Biome> GREY_MOUNTAINS_PEAKS = register("grey_mountains_peaks");
    public static final RegistryKey<Biome> GREY_ASHEN_WOODS = register("grey_ashen_woods");
    public static final RegistryKey<Biome> GREY_FOREST = register("grey_forest");
    public static final RegistryKey<Biome> GREY_PLAINS = register("grey_plains");
    public static final RegistryKey<Biome> HARAD = register("harad");
    public static final RegistryKey<Biome> HARAD_DESERT = register("harad_desert");
    public static final RegistryKey<Biome> HARAD_WOODS = register("harad_woods");
    public static final RegistryKey<Biome> HARONDOR = register("harondor");
    public static final RegistryKey<Biome> HIGH_MOOR_VALE = register("high_moor_vale");
    public static final RegistryKey<Biome> HIGH_MOOR = register("high_moor");
    public static final RegistryKey<Biome> HIGH_MOOR_HILLS = register("high_moor_hills");
    public static final RegistryKey<Biome> HILLS_OF_EVENDIM = register("hills_of_evendim");

    public static final RegistryKey<Biome> IRON_HILLS_PLAINS = register("iron_hills_frontier");
    public static final RegistryKey<Biome> NORTHERN_RHOVANION_FOREST = register("northern_rhovanion_forest");
    public static final RegistryKey<Biome> NORTHERN_RHOVANION_HILLS = register("northern_rhovanion_hills");
    public static final RegistryKey<Biome> DALE_RIVERSIDE = register("dale_riverside");
    public static final RegistryKey<Biome> IRON_FOOTHILLS = register("iron_foothills");
    public static final RegistryKey<Biome> IRON_HILLS_BASE = register("iron_hills_base");
    public static final RegistryKey<Biome> IRON_HILLS = register("iron_hills");
    public static final RegistryKey<Biome> IRON_HILLS_PEAKS = register("iron_hills_peaks");
    public static final RegistryKey<Biome> ISENGARD = register("isengard");
    public static final RegistryKey<Biome> ISENGARD_HILL = register("isengard_hill");
    public static final RegistryKey<Biome> ITHILIEN = register("ithilien");
    public static final RegistryKey<Biome> ITHILIEN_GLADE = register("ithilien_glade");
    public static final RegistryKey<Biome> ITHILIEN_WASTES = register("ithilien_wastes");
    public static final RegistryKey<Biome> ITHILIEN_WASTES_GLADE = register("ithilien_wastes_glade");
    public static final RegistryKey<Biome> LAMEDON = register("lamedon");
    public static final RegistryKey<Biome> LAMEDON_HILLS = register("lamedon_hills");
    public static final RegistryKey<Biome> LEBENNIN = register("lebennin");
    public static final RegistryKey<Biome> LEBENNIN_HILLS = register("lebennin_hills");
    public static final RegistryKey<Biome> LEBENNIN_SHORES = register("lebennin_shores");
    public static final RegistryKey<Biome> LINDON = register("lindon");
    public static final RegistryKey<Biome> LINDON_FOREST = register("lindon_forest");
    public static final RegistryKey<Biome> LINDON_HIDDEN_BLOSSOM = register("lindon_hidden_blossom");
    public static final RegistryKey<Biome> LINDON_MEADOW = register("lindon_meadow");
    public static final RegistryKey<Biome> LONELY_MOUNTAIN_FOOTHILLS = register("lonely_mountain_foothills");
    public static final RegistryKey<Biome> LONELY_MOUNTAIN_BASE = register("lonely_mountain_base");
    public static final RegistryKey<Biome> LONELY_MOUNTAIN = register("lonely_mountain");
    public static final RegistryKey<Biome> LONELY_MOUNTAIN_PEAKS = register("lonely_mountain_peaks");
    public static final RegistryKey<Biome> LONELY_MOUNTAIN_TAIGA = register("lonely_mountain_taiga");
    public static final RegistryKey<Biome> LONG_LAKE = register("long_lake");
    public static final RegistryKey<Biome> LONG_LAKE_SHORES = register("long_lake_shores");
    public static final RegistryKey<Biome> LONG_MARSHES = register("long_marshes");
    public static final RegistryKey<Biome> LORIEN_EDGE = register("lorien_edge");
    public static final RegistryKey<Biome> LOSSARNACH = register("lossarnach");
    public static final RegistryKey<Biome> LOSSARNACH_CHERRY_BLOSSOM = register("lossarnach_cherry_blossom");
    public static final RegistryKey<Biome> LOSSARNACH_VALLEY = register("lossarnach_valley");
    public static final RegistryKey<Biome> LOSSARNACH_VALLEY_RED = register("lossarnach_valley_red");
    public static final RegistryKey<Biome> LOSSARNACH_VALLEY_ORANGE = register("lossarnach_valley_orange");
    public static final RegistryKey<Biome> LOSSARNACH_VALLEY_YELLOW = register("lossarnach_valley_yellow");
    public static final RegistryKey<Biome> LOSSARNACH_VALLEY_GREEN = register("lossarnach_valley_green");
    public static final RegistryKey<Biome> LOTHLORIEN = register("lothlorien");
    public static final RegistryKey<Biome> LOTHLORIEN_GLADE = register("lothlorien_glade");
    public static final RegistryKey<Biome> LOTHLORIEN_BLOSSOM = register("lothlorien_blossom");
    public static final RegistryKey<Biome> MINHIRIATH = register("minhiriath");
    public static final RegistryKey<Biome> MINHIRIATH_WHEAT_FIELD = register("minhiriath_wheat_field");

    public static final RegistryKey<Biome> MIRKWOOD = register("mirkwood");
    public static final RegistryKey<Biome> MIRKWOOD_EDGE = register("mirkwood_edge");
    public static final RegistryKey<Biome> MIRKWOOD_FOOTHILLS = register("mirkwood_foothills");
    public static final RegistryKey<Biome> MIRKWOOD_MOUNTAINS_BASE = register("mirkwood_mountains_base");
    public static final RegistryKey<Biome> MIRKWOOD_MOUNTAINS = register("mirkwood_mountains");
    public static final RegistryKey<Biome> MIRKWOOD_MOUNTAINS_PEAKS = register("mirkwood_mountains_peaks");
    public static final RegistryKey<Biome> MIRKWOOD_SWAMP = register("mirkwood_swamp");
    public static final RegistryKey<Biome> GREAT_RIVER = register("great_river");
    public static final RegistryKey<Biome> GUNDABAD_PLAINS = register("gundabad_plains");
    public static final RegistryKey<Biome> GUNDABAD_WOODS = register("gundabad_woods");
    public static final RegistryKey<Biome> MANGROVE_POND = register("mangrove_pond");
    public static final RegistryKey<Biome> MIRKWOOD_MARSHES = register("mirkwood_marshes");
    public static final RegistryKey<Biome> MISTY_MOUNTAINS_BASE = register("misty_mountains_base");
    public static final RegistryKey<Biome> MISTY_MOUNTAINS = register("misty_mountains");
    public static final RegistryKey<Biome> MISTY_MOUNTAINS_PEAKS  = register("misty_mountains_peaks");
    public static final RegistryKey<Biome> MORDOR = register("mordor");
    public static final RegistryKey<Biome> MORDOR_ASHEN_FOREST = register("mordor_ashen_forest");
    public static final RegistryKey<Biome> MORDOR_HILL = register("mordor_hill");
    public static final RegistryKey<Biome> MORDOR_WASTES = register("mordor_wastes");
    public static final RegistryKey<Biome> MORGUL_VALE = register("morgul_vale");
    public static final RegistryKey<Biome> MORGUL_FOREST = register("morgul_forest");
    public static final RegistryKey<Biome> MORGUL_RIVER = register("morgul_river");
    public static final RegistryKey<Biome> MOUNT_GUNDABAD_BASE = register("mount_gundabad_base");
    public static final RegistryKey<Biome> MOUNT_GUNDABAD = register("mount_gundabad");
    public static final RegistryKey<Biome> MOUNT_GUNDABAD_PEAKS = register("mount_gundabad_peaks");
    public static final RegistryKey<Biome> MOUNT_DOOM = register("mount_doom");
    public static final RegistryKey<Biome> MOUNT_DOOM_PIT = register("mount_doom_pit");
    public static final RegistryKey<Biome> NAN_CURUNIR = register("nan_curunir");
    public static final RegistryKey<Biome> NEN_HITHOEL = register("nen_hithoel");
    public static final RegistryKey<Biome> NEN_HITHOEL_RAPIDS = register("nen_hithoel_rapids");
    public static final RegistryKey<Biome> NEN_HITHOEL_SHORES = register("nen_hithoel_shores");
    public static final RegistryKey<Biome> NEN_HITHOEL_FOREST = register("nen_hithoel_forest");
    public static final RegistryKey<Biome> NINDALF = register("nindalf");
    public static final RegistryKey<Biome> NORTH_DOWNS = register("north_downs");
    public static final RegistryKey<Biome> NORTHERN_DUNLAND_GLADE = register("northern_dunland_glade");
    public static final RegistryKey<Biome> NORTHERN_MIRKWOOD_MARSHES = register("northern_mirkwood_marshes");
    public static final RegistryKey<Biome> NORTHERN_MIRKWOOD_SWAMP = register("northern_mirkwood_swamp");
    public static final RegistryKey<Biome> NORTHERN_WASTELANDS = register("northern_wastelands");
    public static final RegistryKey<Biome> NURN = register("nurn");
    public static final RegistryKey<Biome> NURN_FOREST = register("nurn_forest");
    public static final RegistryKey<Biome> NURN_HILL = register("nurn_hill");
    public static final RegistryKey<Biome> NURN_EDGE = register("nurn_edge");
    public static final RegistryKey<Biome> NURN_EDGE_WOODS = register("nurn_edge_woods");
    public static final RegistryKey<Biome> NURN_RIVER = register("nurn_river");
    public static final RegistryKey<Biome> NURN_SEA = register("nurn_sea");
    public static final RegistryKey<Biome> OASIS = register("oasis");
    public static final RegistryKey<Biome> OCEAN = register("ocean");
    public static final RegistryKey<Biome> OCEAN_COAST = register("ocean_coast");
    public static final RegistryKey<Biome> OLD_ANGMAR = register("old_angmar");
    public static final RegistryKey<Biome> OLD_ANGMAR_FOREST = register("old_angmar_forest");
    public static final RegistryKey<Biome> OLD_ANGMAR_COLD_HILL = register("old_angmar_cold_hill");
    public static final RegistryKey<Biome> OLD_ANGMAR_FROZEN_HILL = register("old_angmar_frozen_hill");
    public static final RegistryKey<Biome> OLD_ARTHEDAIN = register("old_arthedain");
    public static final RegistryKey<Biome> OLD_ARTHEDAIN_FOREST = register("old_arthedain_forest");
    public static final RegistryKey<Biome> OLD_ARTHEDAIN_MEADOW = register("old_arthedain_meadow");
    public static final RegistryKey<Biome> OLD_ARTHEDAIN_FOOTHILL = register("old_arthedain_foothill");
    public static final RegistryKey<Biome> OLD_CARDOLAN = register("old_cardolan");
    public static final RegistryKey<Biome> OLD_CARDOLAN_FOREST = register("old_cardolan_forest");
    public static final RegistryKey<Biome> OLD_CARDOLAN_HILL = register("old_cardolan_hill");
    public static final RegistryKey<Biome> OLD_RHUDAUR = register("old_rhudaur");
    public static final RegistryKey<Biome> OLD_RHUDAUR_FOREST = register("old_rhudaur_forest");
    public static final RegistryKey<Biome> OLD_RHUDAUR_HILL = register("old_rhudaur_hill");
    public static final RegistryKey<Biome> OSGILIATH = register("osgiliath");
    public static final RegistryKey<Biome> PELENNOR_FIELDS = register("pelennor_fields");
    public static final RegistryKey<Biome> PELENNOR_WHEAT_FIELD = register("pelennor_wheat_field");
    public static final RegistryKey<Biome> POND = register("pond");
    public static final RegistryKey<Biome> RHUN = register("rhun");
    public static final RegistryKey<Biome> RHUN_FIELD = register("rhun_field");
    public static final RegistryKey<Biome> RHUN_FOREST = register("rhun_forest");
    public static final RegistryKey<Biome> RHUN_HIDDEN_BLOSSOM = register("rhun_hidden_blossom");
    public static final RegistryKey<Biome> SEA_OF_RHUN = register("sea_of_rhun");
    public static final RegistryKey<Biome> RIVER = register("river");
    public static final RegistryKey<Biome> RIVER_RUNNING = register("river_running");
    public static final RegistryKey<Biome> ROHAN = register("rohan");
    public static final RegistryKey<Biome> ROHAN_FOREST = register("rohan_forest");
    public static final RegistryKey<Biome> ROHAN_FIELD = register("rohan_field");
    public static final RegistryKey<Biome> SARN_GEBIR_SHORES = register("sarn_gebir_shores");
    public static final RegistryKey<Biome> SARN_GEBIR_WILDLANDS = register("sarn_gebir_wildlands");
    public static final RegistryKey<Biome> SHIRE = register("shire");
    public static final RegistryKey<Biome> SHIRE_EDGE = register("shire_edge");
    public static final RegistryKey<Biome> SHIRE_FOREST = register("shire_forest");
    public static final RegistryKey<Biome> SHIRE_HILLS = register("shire_hills");
    public static final RegistryKey<Biome> SHIRE_WOODS = register("shire_woods");
    public static final RegistryKey<Biome> SOUTHEAST_RHOVANION = register("southeast_rhovanion");
    public static final RegistryKey<Biome> SOUTHEAST_RHOVANION_FIELD = register("southeast_rhovanion_field");
    public static final RegistryKey<Biome> SOUTHERN_FOROCHEL = register("southern_forochel");
    public static final RegistryKey<Biome> THE_ANGLE = register("the_angle");
    public static final RegistryKey<Biome> THE_OLD_FOREST = register("the_old_forest");
    public static final RegistryKey<Biome> THE_WHITE_DOWNS = register("the_white_downs");
    public static final RegistryKey<Biome> THE_WOLD = register("the_wold");
    public static final RegistryKey<Biome> THE_WOLD_WHEAT_FIELD = register("the_wold_wheat_field");
    public static final RegistryKey<Biome> TOLFALAS = register("tolfalas");
    public static final RegistryKey<Biome> TOROGWAITH = register("torogwaith");
    public static final RegistryKey<Biome> TROLLSHAWS = register("trollshaws");
    public static final RegistryKey<Biome> UDUN = register("udun");
    public static final RegistryKey<Biome> UMBAR = register("umbar");
    public static final RegistryKey<Biome> UMBAR_WOODS = register("umbar_woods");
    public static final RegistryKey<Biome> WEBBED_WOODS = register("webbed_woods");
    public static final RegistryKey<Biome> WEBBED_DARK_WOODS = register("webbed_dark_woods");
    public static final RegistryKey<Biome> WITHERED_HEATH = register("withered_heath");
    public static final RegistryKey<Biome> WASTE_POND = register("waste_pond");
    public static final RegistryKey<Biome> WHITE_MOUNTAINS_BASE = register("white_mountains_base");
    public static final RegistryKey<Biome> WHITE_MOUNTAINS = register("white_mountains");
    public static final RegistryKey<Biome> WHITE_MOUNTAINS_PEAKS = register("white_mountains_peaks");

    public static final RegistryKey<Biome> WOODLAND_REALM = register("woodland_realm");
    public static final RegistryKey<Biome> WOODLAND_FOOTHILLS= register("woodland_foothills");
    public static final RegistryKey<Biome> WOODLAND_GLADE = register("woodland_glade");
    public static final RegistryKey<Biome> AUTUMN_WOODLAND = register("autumn_woodland");
    public static final RegistryKey<Biome> WOODLAND_HILLS = register("woodland_hills");
    // endregion

    // region CAVES
    public static final RegistryKey<Biome> BASIC_CAVE = register("basic_cave");
    public static final RegistryKey<Biome> LUSH_CAVE = register("lush_cave");
    public static final RegistryKey<Biome> DRIPSTONE_CAVE = register("dripstone_cave");
    public static final RegistryKey<Biome> DOLOMITE_CAVE = register("dolomite_cave");
    public static final RegistryKey<Biome> GALONN_CAVE = register("galonn_cave");
    public static final RegistryKey<Biome> GILDED_CAVE = register("gilded_cave");
    public static final RegistryKey<Biome> IZHERABAN_CAVE = register("izheraban_cave");
    public static final RegistryKey<Biome> LIMESTONE_CAVE = register("limestone_cave");
    public static final RegistryKey<Biome> MOUNTAIN_CAVE = register("mountain_cave");
    public static final RegistryKey<Biome> MUD_CAVE = register("mud_cave");
    public static final RegistryKey<Biome> FUNGUS_CAVE = register("fungus_cave");
    public static final RegistryKey<Biome> BASALT_CAVE = register("basalt_cave");
    public static final RegistryKey<Biome> MAGMA_CAVE = register("magma_cave");
    public static final RegistryKey<Biome> MITHRIL_CAVE = register("mithril_cave");
    public static final RegistryKey<Biome> DRY_CAVE = register("dry_cave");
    public static final RegistryKey<Biome> ICE_CAVE = register("ice_cave");

    // endregion

    private static RegistryKey<Biome> register(String name) {
        TranslationEntries.biomeEntries.add(name);
        Identifier biomeId = MiddleEarth.id(name);
        RegistryKey<Biome> biome = RegistryKey.of(RegistryKeys.BIOME, biomeId);
        BiomeEventRegistryUtil.addBiomeEntry(biome);
        return biome;
    }

    public static void registerModBiomes() {
        MiddleEarth.LOGGER.logDebugMsg("Registering ModBiomes for " + MiddleEarth.MOD_ID);
    }
}
