package net.sevenstars.middleearth.world.biomes;

import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.level.biome.Biome;
import net.minecraft.world.level.biome.Biomes;
import net.sevenstars.middleearth.MiddleEarth;
import net.sevenstars.middleearth.datageneration.content.TranslationEntries;
import net.sevenstars.middleearth.registries.content.biomevents.BiomeEventRegistryUtil;

public class MEBiomeKeys extends Biomes {
    // region SURFACE
    public static final ResourceKey<Biome> ANDUIN_VALES = MEBiomeKeys.register("anduin_vales");
    public static final ResourceKey<Biome> ANDUIN_VALES_FOREST = MEBiomeKeys.register("anduin_vales_forest");
    public static final ResourceKey<Biome> ANORIEN = MEBiomeKeys.register("anorien");
    public static final ResourceKey<Biome> ANORIEN_RIVERSIDE = MEBiomeKeys.register("anorien_riverside");
    public static final ResourceKey<Biome> ANORIEN_FOOTHILLS = MEBiomeKeys.register("anorien_foothills");
    public static final ResourceKey<Biome> BARROW_DOWNS = MEBiomeKeys.register("barrow_downs");
    public static final ResourceKey<Biome> BELERIAND_ISLAND = MEBiomeKeys.register("beleriand_island");
    public static final ResourceKey<Biome> BELFALAS = MEBiomeKeys.register("belfalas");
    public static final ResourceKey<Biome> BELFALAS_FOREST = MEBiomeKeys.register("belfalas_forest");
    public static final ResourceKey<Biome> BELFALAS_HILLS = MEBiomeKeys.register("belfalas_hills");
    public static final ResourceKey<Biome> BELFALAS_BEACH = MEBiomeKeys.register("belfalas_beach");
    public static final ResourceKey<Biome> BLACKROOT_VALE = MEBiomeKeys.register("blackroot_vale");
    public static final ResourceKey<Biome> BLACKROOT_FOREST = MEBiomeKeys.register("blackroot_forest");
    public static final ResourceKey<Biome> BLUE_MOUNTAINS_FOOTHILLS = MEBiomeKeys.register("blue_mountains_foothills");
    public static final ResourceKey<Biome> BLUE_MOUNTAINS_BASE = MEBiomeKeys.register("blue_mountains_base");
    public static final ResourceKey<Biome> BLUE_MOUNTAINS = MEBiomeKeys.register("blue_mountains");
    public static final ResourceKey<Biome> BLUE_MOUNTAINS_HIGH_LANDS = MEBiomeKeys.register("blue_mountains_high_lands");
    public static final ResourceKey<Biome> BLUE_MOUNTAINS_PEAKS = MEBiomeKeys.register("blue_mountains_peaks");
    public static final ResourceKey<Biome> BLUE_MOUNTAINS_WOODS = MEBiomeKeys.register("blue_mountains_woods");
    public static final ResourceKey<Biome> BROWN_LANDS = MEBiomeKeys.register("brown_lands");
    public static final ResourceKey<Biome> CARADHRAS_BASE = MEBiomeKeys.register("caradhras_base");
    public static final ResourceKey<Biome> CARADHRAS = MEBiomeKeys.register("caradhras");
    public static final ResourceKey<Biome> CARADHRAS_PEAKS = MEBiomeKeys.register("caradhras_peaks");
    public static final ResourceKey<Biome> CELEBDIL_BASE = MEBiomeKeys.register("celebdil_base");
    public static final ResourceKey<Biome> CELEBDIL = MEBiomeKeys.register("celebdil");
    public static final ResourceKey<Biome> CELEBDIL_PEAKS = MEBiomeKeys.register("celebdil_peaks");
    public static final ResourceKey<Biome> CORSAIR_COASTS = MEBiomeKeys.register("corsair_coasts");
    public static final ResourceKey<Biome> DALE = MEBiomeKeys.register("dale");
    public static final ResourceKey<Biome> DALE_FOREST = MEBiomeKeys.register("dale_forest");
    public static final ResourceKey<Biome> DALE_MEADOW = MEBiomeKeys.register("dale_meadow");
    public static final ResourceKey<Biome> DALE_CITY = MEBiomeKeys.register("dale_city");
    public static final ResourceKey<Biome> DAGORLAD = MEBiomeKeys.register("dagorlad");
    public static final ResourceKey<Biome> DARK_MIRKWOOD = MEBiomeKeys.register("dark_mirkwood");
    public static final ResourceKey<Biome> DARK_MIRKWOOD_EDGE = MEBiomeKeys.register("dark_mirkwood_edge");
    public static final ResourceKey<Biome> DARK_ANDUIN_VALES = MEBiomeKeys.register("dark_anduin_vales");
    public static final ResourceKey<Biome> DEAD_MARSHES = MEBiomeKeys.register("dead_marshes");
    public static final ResourceKey<Biome> DEAD_MARSHES_WATER = MEBiomeKeys.register("dead_marshes_water");
    public static final ResourceKey<Biome> DESOLATED_LANDS = MEBiomeKeys.register("desolated_lands");
    public static final ResourceKey<Biome> DOL_GULDUR = MEBiomeKeys.register("dol_guldur");
    public static final ResourceKey<Biome> DOL_GULDUR_HILL = MEBiomeKeys.register("dol_guldur_hill");
    public static final ResourceKey<Biome> DORWINION = MEBiomeKeys.register("dorwinion");
    public static final ResourceKey<Biome> DORWINION_LAVENDER_FIELD = MEBiomeKeys.register("dorwinion_lavender_field");
    public static final ResourceKey<Biome> DORWINION_HILLS = MEBiomeKeys.register("dorwinion_hills");
    public static final ResourceKey<Biome> DRUWAITH_IAUR = MEBiomeKeys.register("druwaith_iaur");
    public static final ResourceKey<Biome> DUNLAND = MEBiomeKeys.register("dunland");
    public static final ResourceKey<Biome> DUNLAND_FOOTHILLS = MEBiomeKeys.register("dunland_foothills");
    public static final ResourceKey<Biome> DUNLAND_HILLS = MEBiomeKeys.register("dunland_hills");
    public static final ResourceKey<Biome> EAST_BIGHT = MEBiomeKeys.register("east_bight");
    public static final ResourceKey<Biome> EASTERN_NURN = MEBiomeKeys.register("eastern_nurn");
    public static final ResourceKey<Biome> EASTERN_RHOVANION = MEBiomeKeys.register("eastern_rhovanion");
    public static final ResourceKey<Biome> EASTERN_RHOVANION_FOREST = MEBiomeKeys.register("eastern_rhovanion_forest");
    public static final ResourceKey<Biome> EMYN_MUIL = MEBiomeKeys.register("emyn_muil");
    public static final ResourceKey<Biome> EMYN_MUIL_CLIFFS = MEBiomeKeys.register("emyn_muil_cliffs");
    public static final ResourceKey<Biome> EMYN_MUIL_PEAKS = MEBiomeKeys.register("emyn_muil_peaks");
    public static final ResourceKey<Biome> EMYN_MUIL_POND = MEBiomeKeys.register("emyn_muil_pond");
    public static final ResourceKey<Biome> ENEDWAITH = MEBiomeKeys.register("enedwaith");
    public static final ResourceKey<Biome> ENEDWAITH_FIELD = MEBiomeKeys.register("enedwaith_field");
    public static final ResourceKey<Biome> ENEDWAITH_WHEAT_FIELD = MEBiomeKeys.register("enedwaith_wheat_field");
    public static final ResourceKey<Biome> EPHEL_DUATH = MEBiomeKeys.register("ephel_duath");
    public static final ResourceKey<Biome> EPHEL_DUATH_BASE = MEBiomeKeys.register("ephel_duath_base");
    public static final ResourceKey<Biome> EPHEL_DUATH_PEAKS = MEBiomeKeys.register("ephel_duath_peaks");
    public static final ResourceKey<Biome> ERED_LITHUI = MEBiomeKeys.register("ered_lithui");
    public static final ResourceKey<Biome> ERED_LITHUI_BASE = MEBiomeKeys.register("ered_lithui_base");
    public static final ResourceKey<Biome> ERED_LITHUI_PEAKS = MEBiomeKeys.register("ered_lithui_peaks");
    public static final ResourceKey<Biome> EREGION = MEBiomeKeys.register("eregion");
    public static final ResourceKey<Biome> EREGION_FOREST = MEBiomeKeys.register("eregion_forest");
    public static final ResourceKey<Biome> EREGION_GLADE = MEBiomeKeys.register("eregion_glade");
    public static final ResourceKey<Biome> ETHIR_ANDUIN = MEBiomeKeys.register("ethir_anduin");
    public static final ResourceKey<Biome> ETHIR_ANDUIN_RIVER_DELTA = MEBiomeKeys.register("ethir_anduin_river_delta");
    public static final ResourceKey<Biome> FANGORN = MEBiomeKeys.register("fangorn");
    public static final ResourceKey<Biome> FANGORN_FOOTHILLS = MEBiomeKeys.register("fangorn_foothills");
    public static final ResourceKey<Biome> FANUIDHOL_BASE = MEBiomeKeys.register("fanuidhol_base");
    public static final ResourceKey<Biome> FANUIDHOL = MEBiomeKeys.register("fanuidhol");
    public static final ResourceKey<Biome> FANUIDHOL_PEAKS = MEBiomeKeys.register("fanuidhol_peaks");
    public static final ResourceKey<Biome> MIRKWOOD_RIVER = MEBiomeKeys.register("mirkwood_river");
    public static final ResourceKey<Biome> FORODWAITH = MEBiomeKeys.register("forodwaith");
    public static final ResourceKey<Biome> FROZEN_OCEAN = MEBiomeKeys.register("frozen_ocean");
    public static final ResourceKey<Biome> FROZEN_POND = MEBiomeKeys.register("frozen_pond");
    public static final ResourceKey<Biome> LINDON_SHORES = MEBiomeKeys.register("lindon_shores");
    public static final ResourceKey<Biome> LINDON_SHORES_CLIFFS = MEBiomeKeys.register("lindon_shores_cliffs");
    public static final ResourceKey<Biome> GONDOR = MEBiomeKeys.register("gondor");
    public static final ResourceKey<Biome> GONDOR_FOREST = MEBiomeKeys.register("gondor_forest");
    public static final ResourceKey<Biome> GONDOR_HILL = MEBiomeKeys.register("gondor_hill");
    public static final ResourceKey<Biome> GORGOROTH = MEBiomeKeys.register("gorgoroth");
    public static final ResourceKey<Biome> GORGOROTH_ASHEN_WOODS = MEBiomeKeys.register("gorgoroth_ashen_woods");
    public static final ResourceKey<Biome> GORGOROTH_DELTA = MEBiomeKeys.register("gorgoroth_delta");
    public static final ResourceKey<Biome> GREY_MOUNTAINS = MEBiomeKeys.register("grey_mountains");
    public static final ResourceKey<Biome> GREY_MOUNTAINS_BASE = MEBiomeKeys.register("grey_mountains_base");
    public static final ResourceKey<Biome> GREY_MOUNTAINS_PEAKS = MEBiomeKeys.register("grey_mountains_peaks");
    public static final ResourceKey<Biome> GREY_ASHEN_WOODS = MEBiomeKeys.register("grey_ashen_woods");
    public static final ResourceKey<Biome> GREY_FOREST = MEBiomeKeys.register("grey_forest");
    public static final ResourceKey<Biome> GREY_PLAINS = MEBiomeKeys.register("grey_plains");
    public static final ResourceKey<Biome> HARAD = MEBiomeKeys.register("harad");
    public static final ResourceKey<Biome> HARAD_DESERT = MEBiomeKeys.register("harad_desert");
    public static final ResourceKey<Biome> HARAD_WOODS = MEBiomeKeys.register("harad_woods");
    public static final ResourceKey<Biome> HARONDOR = MEBiomeKeys.register("harondor");
    public static final ResourceKey<Biome> HIGH_MOOR_VALE = MEBiomeKeys.register("high_moor_vale");
    public static final ResourceKey<Biome> HIGH_MOOR = MEBiomeKeys.register("high_moor");
    public static final ResourceKey<Biome> HIGH_MOOR_HILLS = MEBiomeKeys.register("high_moor_hills");
    public static final ResourceKey<Biome> HILLS_OF_EVENDIM = MEBiomeKeys.register("hills_of_evendim");

    public static final ResourceKey<Biome> IRON_HILLS_PLAINS = MEBiomeKeys.register("iron_hills_frontier");
    public static final ResourceKey<Biome> NORTHERN_RHOVANION_FOREST = MEBiomeKeys.register("northern_rhovanion_forest");
    public static final ResourceKey<Biome> NORTHERN_RHOVANION_HILLS = MEBiomeKeys.register("northern_rhovanion_hills");
    public static final ResourceKey<Biome> DALE_RIVERSIDE = MEBiomeKeys.register("dale_riverside");
    public static final ResourceKey<Biome> IRON_FOOTHILLS = MEBiomeKeys.register("iron_foothills");
    public static final ResourceKey<Biome> IRON_HILLS_BASE = MEBiomeKeys.register("iron_hills_base");
    public static final ResourceKey<Biome> IRON_HILLS = MEBiomeKeys.register("iron_hills");
    public static final ResourceKey<Biome> IRON_HILLS_PEAKS = MEBiomeKeys.register("iron_hills_peaks");
    public static final ResourceKey<Biome> ISENGARD = MEBiomeKeys.register("isengard");
    public static final ResourceKey<Biome> ISENGARD_HILL = MEBiomeKeys.register("isengard_hill");
    public static final ResourceKey<Biome> ITHILIEN = MEBiomeKeys.register("ithilien");
    public static final ResourceKey<Biome> ITHILIEN_GLADE = MEBiomeKeys.register("ithilien_glade");
    public static final ResourceKey<Biome> ITHILIEN_WASTES = MEBiomeKeys.register("ithilien_wastes");
    public static final ResourceKey<Biome> ITHILIEN_WASTES_GLADE = MEBiomeKeys.register("ithilien_wastes_glade");
    public static final ResourceKey<Biome> LAMEDON = MEBiomeKeys.register("lamedon");
    public static final ResourceKey<Biome> LAMEDON_HILLS = MEBiomeKeys.register("lamedon_hills");
    public static final ResourceKey<Biome> LEBENNIN = MEBiomeKeys.register("lebennin");
    public static final ResourceKey<Biome> LEBENNIN_HILLS = MEBiomeKeys.register("lebennin_hills");
    public static final ResourceKey<Biome> LEBENNIN_SHORES = MEBiomeKeys.register("lebennin_shores");
    public static final ResourceKey<Biome> LINDON = MEBiomeKeys.register("lindon");
    public static final ResourceKey<Biome> LINDON_FOREST = MEBiomeKeys.register("lindon_forest");
    public static final ResourceKey<Biome> LINDON_HIDDEN_BLOSSOM = MEBiomeKeys.register("lindon_hidden_blossom");
    public static final ResourceKey<Biome> LINDON_MEADOW = MEBiomeKeys.register("lindon_meadow");
    public static final ResourceKey<Biome> LONELY_MOUNTAIN_FOOTHILLS = MEBiomeKeys.register("lonely_mountain_foothills");
    public static final ResourceKey<Biome> LONELY_MOUNTAIN_BASE = MEBiomeKeys.register("lonely_mountain_base");
    public static final ResourceKey<Biome> LONELY_MOUNTAIN = MEBiomeKeys.register("lonely_mountain");
    public static final ResourceKey<Biome> LONELY_MOUNTAIN_PEAKS = MEBiomeKeys.register("lonely_mountain_peaks");
    public static final ResourceKey<Biome> LONELY_MOUNTAIN_TAIGA = MEBiomeKeys.register("lonely_mountain_taiga");
    public static final ResourceKey<Biome> LONG_LAKE = MEBiomeKeys.register("long_lake");
    public static final ResourceKey<Biome> LONG_LAKE_SHORES = MEBiomeKeys.register("long_lake_shores");
    public static final ResourceKey<Biome> LONG_MARSHES = MEBiomeKeys.register("long_marshes");
    public static final ResourceKey<Biome> LORIEN_EDGE = MEBiomeKeys.register("lorien_edge");
    public static final ResourceKey<Biome> LOSSARNACH = MEBiomeKeys.register("lossarnach");
    public static final ResourceKey<Biome> LOSSARNACH_CHERRY_BLOSSOM = MEBiomeKeys.register("lossarnach_cherry_blossom");
    public static final ResourceKey<Biome> LOSSARNACH_VALLEY = MEBiomeKeys.register("lossarnach_valley");
    public static final ResourceKey<Biome> LOSSARNACH_VALLEY_RED = MEBiomeKeys.register("lossarnach_valley_red");
    public static final ResourceKey<Biome> LOSSARNACH_VALLEY_ORANGE = MEBiomeKeys.register("lossarnach_valley_orange");
    public static final ResourceKey<Biome> LOSSARNACH_VALLEY_YELLOW = MEBiomeKeys.register("lossarnach_valley_yellow");
    public static final ResourceKey<Biome> LOSSARNACH_VALLEY_GREEN = MEBiomeKeys.register("lossarnach_valley_green");
    public static final ResourceKey<Biome> LOTHLORIEN = MEBiomeKeys.register("lothlorien");
    public static final ResourceKey<Biome> LOTHLORIEN_GLADE = MEBiomeKeys.register("lothlorien_glade");
    public static final ResourceKey<Biome> LOTHLORIEN_BLOSSOM = MEBiomeKeys.register("lothlorien_blossom");
    public static final ResourceKey<Biome> MINHIRIATH = MEBiomeKeys.register("minhiriath");
    public static final ResourceKey<Biome> MINHIRIATH_WHEAT_FIELD = MEBiomeKeys.register("minhiriath_wheat_field");

    public static final ResourceKey<Biome> MIRKWOOD = MEBiomeKeys.register("mirkwood");
    public static final ResourceKey<Biome> MIRKWOOD_EDGE = MEBiomeKeys.register("mirkwood_edge");
    public static final ResourceKey<Biome> MIRKWOOD_FOOTHILLS = MEBiomeKeys.register("mirkwood_foothills");
    public static final ResourceKey<Biome> MIRKWOOD_MOUNTAINS_BASE = MEBiomeKeys.register("mirkwood_mountains_base");
    public static final ResourceKey<Biome> MIRKWOOD_MOUNTAINS = MEBiomeKeys.register("mirkwood_mountains");
    public static final ResourceKey<Biome> MIRKWOOD_MOUNTAINS_PEAKS = MEBiomeKeys.register("mirkwood_mountains_peaks");
    public static final ResourceKey<Biome> MIRKWOOD_SWAMP = MEBiomeKeys.register("mirkwood_swamp");
    public static final ResourceKey<Biome> GREAT_RIVER = MEBiomeKeys.register("great_river");
    public static final ResourceKey<Biome> GUNDABAD_PLAINS = MEBiomeKeys.register("gundabad_plains");
    public static final ResourceKey<Biome> GUNDABAD_WOODS = MEBiomeKeys.register("gundabad_woods");
    public static final ResourceKey<Biome> MANGROVE_POND = MEBiomeKeys.register("mangrove_pond");
    public static final ResourceKey<Biome> MIRKWOOD_MARSHES = MEBiomeKeys.register("mirkwood_marshes");
    public static final ResourceKey<Biome> MISTY_MOUNTAINS_BASE = MEBiomeKeys.register("misty_mountains_base");
    public static final ResourceKey<Biome> MISTY_MOUNTAINS = MEBiomeKeys.register("misty_mountains");
    public static final ResourceKey<Biome> MISTY_MOUNTAINS_PEAKS  = MEBiomeKeys.register("misty_mountains_peaks");
    public static final ResourceKey<Biome> MORDOR = MEBiomeKeys.register("mordor");
    public static final ResourceKey<Biome> MORDOR_ASHEN_FOREST = MEBiomeKeys.register("mordor_ashen_forest");
    public static final ResourceKey<Biome> MORDOR_HILL = MEBiomeKeys.register("mordor_hill");
    public static final ResourceKey<Biome> MORDOR_WASTES = MEBiomeKeys.register("mordor_wastes");
    public static final ResourceKey<Biome> MORGUL_VALE = MEBiomeKeys.register("morgul_vale");
    public static final ResourceKey<Biome> MORGUL_FOREST = MEBiomeKeys.register("morgul_forest");
    public static final ResourceKey<Biome> MORGUL_RIVER = MEBiomeKeys.register("morgul_river");
    public static final ResourceKey<Biome> MOUNT_GUNDABAD_BASE = MEBiomeKeys.register("mount_gundabad_base");
    public static final ResourceKey<Biome> MOUNT_GUNDABAD = MEBiomeKeys.register("mount_gundabad");
    public static final ResourceKey<Biome> MOUNT_GUNDABAD_PEAKS = MEBiomeKeys.register("mount_gundabad_peaks");
    public static final ResourceKey<Biome> MOUNT_DOOM = MEBiomeKeys.register("mount_doom");
    public static final ResourceKey<Biome> MOUNT_DOOM_PIT = MEBiomeKeys.register("mount_doom_pit");
    public static final ResourceKey<Biome> NAN_CURUNIR = MEBiomeKeys.register("nan_curunir");
    public static final ResourceKey<Biome> NEN_HITHOEL = MEBiomeKeys.register("nen_hithoel");
    public static final ResourceKey<Biome> NEN_HITHOEL_RAPIDS = MEBiomeKeys.register("nen_hithoel_rapids");
    public static final ResourceKey<Biome> NEN_HITHOEL_SHORES = MEBiomeKeys.register("nen_hithoel_shores");
    public static final ResourceKey<Biome> NEN_HITHOEL_FOREST = MEBiomeKeys.register("nen_hithoel_forest");
    public static final ResourceKey<Biome> NINDALF = MEBiomeKeys.register("nindalf");
    public static final ResourceKey<Biome> NORTH_DOWNS = MEBiomeKeys.register("north_downs");
    public static final ResourceKey<Biome> NORTHERN_DUNLAND_GLADE = MEBiomeKeys.register("northern_dunland_glade");
    public static final ResourceKey<Biome> NORTHERN_MIRKWOOD_MARSHES = MEBiomeKeys.register("northern_mirkwood_marshes");
    public static final ResourceKey<Biome> NORTHERN_MIRKWOOD_SWAMP = MEBiomeKeys.register("northern_mirkwood_swamp");
    public static final ResourceKey<Biome> NORTHERN_WASTELANDS = MEBiomeKeys.register("northern_wastelands");
    public static final ResourceKey<Biome> NURN = MEBiomeKeys.register("nurn");
    public static final ResourceKey<Biome> NURN_FOREST = MEBiomeKeys.register("nurn_forest");
    public static final ResourceKey<Biome> NURN_HILL = MEBiomeKeys.register("nurn_hill");
    public static final ResourceKey<Biome> NURN_EDGE = MEBiomeKeys.register("nurn_edge");
    public static final ResourceKey<Biome> NURN_EDGE_WOODS = MEBiomeKeys.register("nurn_edge_woods");
    public static final ResourceKey<Biome> NURN_RIVER = MEBiomeKeys.register("nurn_river");
    public static final ResourceKey<Biome> NURN_SEA = MEBiomeKeys.register("nurn_sea");
    public static final ResourceKey<Biome> OASIS = MEBiomeKeys.register("oasis");
    public static final ResourceKey<Biome> OCEAN = MEBiomeKeys.register("ocean");
    public static final ResourceKey<Biome> OCEAN_COAST = MEBiomeKeys.register("ocean_coast");
    public static final ResourceKey<Biome> OLD_ANGMAR = MEBiomeKeys.register("old_angmar");
    public static final ResourceKey<Biome> OLD_ANGMAR_FOREST = MEBiomeKeys.register("old_angmar_forest");
    public static final ResourceKey<Biome> OLD_ANGMAR_COLD_HILL = MEBiomeKeys.register("old_angmar_cold_hill");
    public static final ResourceKey<Biome> OLD_ANGMAR_FROZEN_HILL = MEBiomeKeys.register("old_angmar_frozen_hill");
    public static final ResourceKey<Biome> OLD_ARTHEDAIN = MEBiomeKeys.register("old_arthedain");
    public static final ResourceKey<Biome> OLD_ARTHEDAIN_FOREST = MEBiomeKeys.register("old_arthedain_forest");
    public static final ResourceKey<Biome> OLD_ARTHEDAIN_MEADOW = MEBiomeKeys.register("old_arthedain_meadow");
    public static final ResourceKey<Biome> OLD_ARTHEDAIN_FOOTHILL = MEBiomeKeys.register("old_arthedain_foothill");
    public static final ResourceKey<Biome> OLD_CARDOLAN = MEBiomeKeys.register("old_cardolan");
    public static final ResourceKey<Biome> OLD_CARDOLAN_FOREST = MEBiomeKeys.register("old_cardolan_forest");
    public static final ResourceKey<Biome> OLD_CARDOLAN_HILL = MEBiomeKeys.register("old_cardolan_hill");
    public static final ResourceKey<Biome> OLD_RHUDAUR = MEBiomeKeys.register("old_rhudaur");
    public static final ResourceKey<Biome> OLD_RHUDAUR_FOREST = MEBiomeKeys.register("old_rhudaur_forest");
    public static final ResourceKey<Biome> OLD_RHUDAUR_HILL = MEBiomeKeys.register("old_rhudaur_hill");
    public static final ResourceKey<Biome> OSGILIATH = MEBiomeKeys.register("osgiliath");
    public static final ResourceKey<Biome> PELENNOR_FIELDS = MEBiomeKeys.register("pelennor_fields");
    public static final ResourceKey<Biome> PELENNOR_WHEAT_FIELD = MEBiomeKeys.register("pelennor_wheat_field");
    public static final ResourceKey<Biome> POND = MEBiomeKeys.register("pond");
    public static final ResourceKey<Biome> RHUN = MEBiomeKeys.register("rhun");
    public static final ResourceKey<Biome> RHUN_FIELD = MEBiomeKeys.register("rhun_field");
    public static final ResourceKey<Biome> RHUN_FOREST = MEBiomeKeys.register("rhun_forest");
    public static final ResourceKey<Biome> RHUN_HIDDEN_BLOSSOM = MEBiomeKeys.register("rhun_hidden_blossom");
    public static final ResourceKey<Biome> SEA_OF_RHUN = MEBiomeKeys.register("sea_of_rhun");
    public static final ResourceKey<Biome> RIVER = MEBiomeKeys.register("river");
    public static final ResourceKey<Biome> RIVER_RUNNING = MEBiomeKeys.register("river_running");
    public static final ResourceKey<Biome> ROHAN = MEBiomeKeys.register("rohan");
    public static final ResourceKey<Biome> ROHAN_FOREST = MEBiomeKeys.register("rohan_forest");
    public static final ResourceKey<Biome> ROHAN_FIELD = MEBiomeKeys.register("rohan_field");
    public static final ResourceKey<Biome> SARN_GEBIR_SHORES = MEBiomeKeys.register("sarn_gebir_shores");
    public static final ResourceKey<Biome> SARN_GEBIR_WILDLANDS = MEBiomeKeys.register("sarn_gebir_wildlands");
    public static final ResourceKey<Biome> SHIRE = MEBiomeKeys.register("shire");
    public static final ResourceKey<Biome> SHIRE_EDGE = MEBiomeKeys.register("shire_edge");
    public static final ResourceKey<Biome> SHIRE_FOREST = MEBiomeKeys.register("shire_forest");
    public static final ResourceKey<Biome> SHIRE_HILLS = MEBiomeKeys.register("shire_hills");
    public static final ResourceKey<Biome> SHIRE_WOODS = MEBiomeKeys.register("shire_woods");
    public static final ResourceKey<Biome> SOUTHEAST_RHOVANION = MEBiomeKeys.register("southeast_rhovanion");
    public static final ResourceKey<Biome> SOUTHEAST_RHOVANION_FIELD = MEBiomeKeys.register("southeast_rhovanion_field");
    public static final ResourceKey<Biome> SOUTHERN_FOROCHEL = MEBiomeKeys.register("southern_forochel");
    public static final ResourceKey<Biome> THE_ANGLE = MEBiomeKeys.register("the_angle");
    public static final ResourceKey<Biome> THE_OLD_FOREST = MEBiomeKeys.register("the_old_forest");
    public static final ResourceKey<Biome> THE_WHITE_DOWNS = MEBiomeKeys.register("the_white_downs");
    public static final ResourceKey<Biome> THE_WOLD = MEBiomeKeys.register("the_wold");
    public static final ResourceKey<Biome> THE_WOLD_WHEAT_FIELD = MEBiomeKeys.register("the_wold_wheat_field");
    public static final ResourceKey<Biome> TOLFALAS = MEBiomeKeys.register("tolfalas");
    public static final ResourceKey<Biome> TOROGWAITH = MEBiomeKeys.register("torogwaith");
    public static final ResourceKey<Biome> TROLLSHAWS = MEBiomeKeys.register("trollshaws");
    public static final ResourceKey<Biome> UDUN = MEBiomeKeys.register("udun");
    public static final ResourceKey<Biome> UMBAR = MEBiomeKeys.register("umbar");
    public static final ResourceKey<Biome> UMBAR_WOODS = MEBiomeKeys.register("umbar_woods");
    public static final ResourceKey<Biome> WEBBED_WOODS = MEBiomeKeys.register("webbed_woods");
    public static final ResourceKey<Biome> WEBBED_DARK_WOODS = MEBiomeKeys.register("webbed_dark_woods");
    public static final ResourceKey<Biome> WITHERED_HEATH = MEBiomeKeys.register("withered_heath");
    public static final ResourceKey<Biome> WASTE_POND = MEBiomeKeys.register("waste_pond");
    public static final ResourceKey<Biome> WHITE_MOUNTAINS_BASE = MEBiomeKeys.register("white_mountains_base");
    public static final ResourceKey<Biome> WHITE_MOUNTAINS = MEBiomeKeys.register("white_mountains");
    public static final ResourceKey<Biome> WHITE_MOUNTAINS_PEAKS = MEBiomeKeys.register("white_mountains_peaks");

    public static final ResourceKey<Biome> WOODLAND_REALM = MEBiomeKeys.register("woodland_realm");
    public static final ResourceKey<Biome> WOODLAND_FOOTHILLS= MEBiomeKeys.register("woodland_foothills");
    public static final ResourceKey<Biome> WOODLAND_GLADE = MEBiomeKeys.register("woodland_glade");
    public static final ResourceKey<Biome> AUTUMN_WOODLAND = MEBiomeKeys.register("autumn_woodland");
    public static final ResourceKey<Biome> WOODLAND_HILLS = MEBiomeKeys.register("woodland_hills");
    // endregion

    // region CAVES
    public static final ResourceKey<Biome> BASIC_CAVE = MEBiomeKeys.register("basic_cave");
    public static final ResourceKey<Biome> LUSH_CAVE = MEBiomeKeys.register("lush_cave");
    public static final ResourceKey<Biome> DRIPSTONE_CAVE = MEBiomeKeys.register("dripstone_cave");
    public static final ResourceKey<Biome> DOLOMITE_CAVE = MEBiomeKeys.register("dolomite_cave");
    public static final ResourceKey<Biome> GALONN_CAVE = MEBiomeKeys.register("galonn_cave");
    public static final ResourceKey<Biome> GILDED_CAVE = MEBiomeKeys.register("gilded_cave");
    public static final ResourceKey<Biome> IZHERABAN_CAVE = MEBiomeKeys.register("izheraban_cave");
    public static final ResourceKey<Biome> LIMESTONE_CAVE = MEBiomeKeys.register("limestone_cave");
    public static final ResourceKey<Biome> MOUNTAIN_CAVE = MEBiomeKeys.register("mountain_cave");
    public static final ResourceKey<Biome> MUD_CAVE = MEBiomeKeys.register("mud_cave");
    public static final ResourceKey<Biome> FUNGUS_CAVE = MEBiomeKeys.register("fungus_cave");
    public static final ResourceKey<Biome> BASALT_CAVE = MEBiomeKeys.register("basalt_cave");
    public static final ResourceKey<Biome> MAGMA_CAVE = MEBiomeKeys.register("magma_cave");
    public static final ResourceKey<Biome> MITHRIL_CAVE = MEBiomeKeys.register("mithril_cave");
    public static final ResourceKey<Biome> DRY_CAVE = MEBiomeKeys.register("dry_cave");
    public static final ResourceKey<Biome> ICE_CAVE = MEBiomeKeys.register("ice_cave");

    // endregion

    private static ResourceKey<Biome> register(String name) {
        TranslationEntries.biomeEntries.add(name);
        ResourceKey<Biome> biome = ResourceKey.create(Registries.BIOME, MiddleEarth.of(name));
        BiomeEventRegistryUtil.addBiomeEntry(biome);
        return biome;
    }

    public static void registerModBiomes() {
        MiddleEarth.LOGGER.logDebugMsg("Registering ModBiomes for " + MiddleEarth.MOD_ID);
    }
}
