package net.jukoz.me.entity.beasts.warg;

import net.minecraft.client.render.entity.animation.Animation;
import net.minecraft.client.render.entity.animation.AnimationHelper;
import net.minecraft.client.render.entity.animation.Keyframe;
import net.minecraft.client.render.entity.animation.Transformation;
import net.minecraft.client.render.entity.model.EntityModelPartNames;

public class WargAnimations {
	public static final Animation GROWL = Animation.Builder.create(3.0834335f)
			.addBoneAnimation("tail",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(2f, -16f, -3f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("tail",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(-450.13f, -60.01f, -291f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation(EntityModelPartNames.HEAD,
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(-2f, 2f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation(EntityModelPartNames.HEAD,
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(4.43f, 17.49f, -2.61f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.7083433f, AnimationHelper.createRotationalVector(4.99f, 32.04f, -1.29f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("jaw",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.7083433f, AnimationHelper.createRotationalVector(0f, 0f, 7.5f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("lowerBody",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(1f, -8f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("lowerBody",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, -22.5f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("legRight",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(5f, -10f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("legRight",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(-9.96f, -0.87f, -82.42f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armRight",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(2f, -6f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.7083433f, AnimationHelper.createTranslationalVector(-1f, -4f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armRight",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(10.1f, 0.54f, -70.1f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.7083433f, AnimationHelper.createRotationalVector(9.81f, -2.41f, -53.41f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("earRight",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.7083433f, AnimationHelper.createRotationalVector(6.06f, -25.39f, -13.63f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("earLeft",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.7083433f, AnimationHelper.createRotationalVector(-14.74f, 23.06f, -6.17f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("legLeft",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -6f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("legLeft",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(17.06f, 10.59f, -30.91f),
									Transformation.Interpolations.LINEAR))).build();
	public static final Animation GROOM = Animation.Builder.create(4f)
			.addBoneAnimation("tail",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(2f, -16f, -3f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(4f, AnimationHelper.createTranslationalVector(2f, -16f, -3f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("tail",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(-450.13f, -60.01f, -291f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(4f, AnimationHelper.createRotationalVector(-450.13f, -60.01f, -291f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation(EntityModelPartNames.HEAD,
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(-2f, 2f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.8343334f, AnimationHelper.createTranslationalVector(-2f, 1f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.4167667f, AnimationHelper.createTranslationalVector(-2f, 2f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(4f, AnimationHelper.createTranslationalVector(-2f, 2f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation(EntityModelPartNames.HEAD,
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(4.43f, 17.49f, -2.61f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.5f, AnimationHelper.createRotationalVector(15.57f, 18f, 10.79f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.8343334f, AnimationHelper.createRotationalVector(35.16f, 12.59f, 28.05f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.4167667f, AnimationHelper.createRotationalVector(30.16f, 12.59f, 28.05f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.7916767f, AnimationHelper.createRotationalVector(45.16f, 12.59f, 28.05f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2.1676665f, AnimationHelper.createRotationalVector(30.16f, 12.59f, 28.05f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(4f, AnimationHelper.createRotationalVector(4.43f, 17.49f, -2.61f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("jaw",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 15f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.0416767f, AnimationHelper.createRotationalVector(0f, 0f, 22.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.2083433f, AnimationHelper.createRotationalVector(0f, 0f, 5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.4167667f, AnimationHelper.createRotationalVector(0f, 0f, 10f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.5834333f, AnimationHelper.createRotationalVector(0f, 0f, 3.33f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.7916767f, AnimationHelper.createRotationalVector(0f, 0f, 10f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.9583433f, AnimationHelper.createRotationalVector(0f, 0f, 3.33f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2.1676665f, AnimationHelper.createRotationalVector(0f, 0f, 7.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(4f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("lowerBody",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(1f, -9f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1f, AnimationHelper.createTranslationalVector(1f, -8f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2.1676665f, AnimationHelper.createTranslationalVector(1f, -9f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(3f, AnimationHelper.createTranslationalVector(1f, -8f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(4f, AnimationHelper.createTranslationalVector(1f, -9f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("lowerBody",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, -22.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(4f, AnimationHelper.createRotationalVector(0f, 0f, -22.5f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("legRight",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(5f, -10f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(4f, AnimationHelper.createTranslationalVector(5f, -10f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("legRight",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(-9.96f, -0.87f, -82.42f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(4f, AnimationHelper.createRotationalVector(-9.96f, -0.87f, -82.42f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armRight",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(1f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.5f, AnimationHelper.createTranslationalVector(1f, -5f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.125f, AnimationHelper.createTranslationalVector(1f, -4f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(4f, AnimationHelper.createTranslationalVector(1f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armRight",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(3.59f, 10.17f, 3.28f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.5f, AnimationHelper.createRotationalVector(-8.08f, 7.16f, -65.05f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(4.03f, -9.53f, -75.26f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1f, AnimationHelper.createRotationalVector(4.85f, -9.14f, -80.31f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(4f, AnimationHelper.createRotationalVector(3.59f, 10.17f, 3.28f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("earRight",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(4f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("earLeft",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(4f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("legLeft",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(5f, -10f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(4f, AnimationHelper.createTranslationalVector(5f, -10f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("legLeft",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(17.54f, -0.87f, -82.42f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(4f, AnimationHelper.createRotationalVector(17.54f, -0.87f, -82.42f),
									Transformation.Interpolations.LINEAR))).build();
	public static final Animation SITTING_DOWN = Animation.Builder.create(0.75f)
.addBoneAnimation("tail",
						  new Transformation(Transformation.Targets.TRANSLATE,
		new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, -3f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("tail",
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createRotationalVector(2.88f, -29.87f, 79.23f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation(EntityModelPartNames.HEAD,
									  new Transformation(Transformation.Targets.TRANSLATE,
		new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 4f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation(EntityModelPartNames.HEAD,
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 12.5f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("jaw",
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("legRight",
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createRotationalVector(-17.5f, 0f, -65f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armRight",
									  new Transformation(Transformation.Targets.TRANSLATE,
		new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 4f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armRight",
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 22.5f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("earRight",
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(0f, -32.5f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("earLeft",
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 32.5f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("legLeft",
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createRotationalVector(17.5f, 0f, -65f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("warg", 
					new Transformation(Transformation.Targets.TRANSLATE, 
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f), 
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation(EntityModelPartNames.BODY,
									  new Transformation(Transformation.Targets.TRANSLATE,
		new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, -8f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation(EntityModelPartNames.BODY,
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, -22.5f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armLeft",
									  new Transformation(Transformation.Targets.TRANSLATE,
		new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 4f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armLeft",
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 22.5f),
	Transformation.Interpolations.LINEAR))).build();
	public static final Animation STANDING_UP = Animation.Builder.create(0.75f)
.addBoneAnimation("tail",
						  new Transformation(Transformation.Targets.TRANSLATE,
		new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -3f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("tail",
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(2.88f, -29.87f, 79.23f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation(EntityModelPartNames.HEAD,
									  new Transformation(Transformation.Targets.TRANSLATE,
		new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 4f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation(EntityModelPartNames.HEAD,
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 12.5f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("jaw",
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("legRight",
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(-17.5f, 0f, -65f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armRight",
									  new Transformation(Transformation.Targets.TRANSLATE,
		new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 4f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armRight",
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 22.5f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("earRight",
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, -32.5f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("earLeft",
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 32.5f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("legLeft",
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(17.5f, 0f, -65f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("warg",
									  new Transformation(Transformation.Targets.TRANSLATE,
		new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation(EntityModelPartNames.BODY,
									  new Transformation(Transformation.Targets.TRANSLATE,
		new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -8f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation(EntityModelPartNames.BODY,
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, -22.5f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armLeft",
									  new Transformation(Transformation.Targets.TRANSLATE,
		new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 4f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armLeft",
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 22.5f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR))).build();
	public static final Animation SITTING = Animation.Builder.create(0f).looping()
			.addBoneAnimation("tail",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -3f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("tail",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(2.88f, -29.87f, 79.23f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation(EntityModelPartNames.HEAD,
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 4f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation(EntityModelPartNames.HEAD,
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 12.5f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("legRight",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(-17.5f, 0f, -65f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armRight",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 4f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armRight",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 22.5f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("legLeft",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(17.5f, 0f, -65f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("warg",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation(EntityModelPartNames.BODY,
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -8f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation(EntityModelPartNames.BODY,
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, -22.5f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armLeft",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 4f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armLeft",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 22.5f),
									Transformation.Interpolations.LINEAR))).build();
	public static final Animation WALK = Animation.Builder.create(1.75f).looping()
			.addBoneAnimation("warg",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armRight",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0.83f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.4167667f, AnimationHelper.createTranslationalVector(0f, 2.83f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.875f, AnimationHelper.createTranslationalVector(0f, 0.83f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.1676667f, AnimationHelper.createTranslationalVector(0f, -0.25f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.375f, AnimationHelper.createTranslationalVector(-2f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.75f, AnimationHelper.createTranslationalVector(0f, 0.83f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armRight",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 35f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.875f, AnimationHelper.createRotationalVector(0f, 0f, -35f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.1676667f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.375f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.75f, AnimationHelper.createRotationalVector(0f, 0f, 35f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armLeft",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 1f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.2916767f, AnimationHelper.createTranslationalVector(0f, -0.25f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.5416766f, AnimationHelper.createTranslationalVector(-2f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.875f, AnimationHelper.createTranslationalVector(0f, 1f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.2916767f, AnimationHelper.createTranslationalVector(0f, 2.42f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.75f, AnimationHelper.createTranslationalVector(0f, 1f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armLeft",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, -35f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.2916767f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.5416766f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.875f, AnimationHelper.createRotationalVector(0f, 0f, 25f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.75f, AnimationHelper.createRotationalVector(0f, 0f, -35f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation(EntityModelPartNames.HEAD,
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.4167667f, AnimationHelper.createTranslationalVector(0f, 0.5f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.875f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.3433333f, AnimationHelper.createTranslationalVector(0f, 0.5f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation(EntityModelPartNames.HEAD,
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, -7.5f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("tail",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("tail",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 17.5f, 32.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.875f, AnimationHelper.createRotationalVector(0f, -17.5f, 32.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.75f, AnimationHelper.createRotationalVector(0f, 17.5f, 32.5f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("lowerBody",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("lowerBody",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.875f, AnimationHelper.createRotationalVector(5f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.75f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("legLeft",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.4167667f, AnimationHelper.createTranslationalVector(0f, 3f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.875f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.1676667f, AnimationHelper.createTranslationalVector(0f, 0.67f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.375f, AnimationHelper.createTranslationalVector(-2f, 0.84f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("legLeft",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 35f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.875f, AnimationHelper.createRotationalVector(0f, 0f, -35f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.1676667f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.375f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.75f, AnimationHelper.createRotationalVector(0f, 0f, 35f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("legRight",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.2916767f, AnimationHelper.createTranslationalVector(0f, 0.67f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.5416766f, AnimationHelper.createTranslationalVector(-2f, 0.84f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.2916767f, AnimationHelper.createTranslationalVector(0f, 3f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("legRight",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, -45f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.2916767f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.5416766f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.875f, AnimationHelper.createRotationalVector(0f, 0f, 35f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.75f, AnimationHelper.createRotationalVector(0f, 0f, -45f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("bodyFur",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.875f, AnimationHelper.createRotationalVector(5f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.75f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("earRight",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, -50f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("earLeft",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 50f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("jaw",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, -20f),
									Transformation.Interpolations.LINEAR))).build();
	public static final Animation RUN = Animation.Builder.create(0.75f).looping()
			.addBoneAnimation(EntityModelPartNames.HEAD,
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, -12.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.125f, AnimationHelper.createRotationalVector(0f, 0f, -12.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, -12.5f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armRight",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.4583433f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.6766666f, AnimationHelper.createTranslationalVector(0f, 3f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armRight",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, -60f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.375f, AnimationHelper.createRotationalVector(0f, 0f, 25.36f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.4583433f, AnimationHelper.createRotationalVector(0f, 0f, 30f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, -60f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armLeft",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.25f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.5834334f, AnimationHelper.createTranslationalVector(0f, 3f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armLeft",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, -60f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, 0f, 27.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, -60f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation(EntityModelPartNames.BODY,
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 1f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.375f, AnimationHelper.createTranslationalVector(0f, -2f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 1f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation(EntityModelPartNames.BODY,
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, -7.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.375f, AnimationHelper.createRotationalVector(0f, 0f, 5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, -7.5f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("tail",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(-1f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.375f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(-1f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("tail",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 85f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.375f, AnimationHelper.createRotationalVector(0f, 0f, 105f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 85f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("legLeft",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.08343333f, AnimationHelper.createTranslationalVector(0f, 2f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.20834334f, AnimationHelper.createTranslationalVector(0f, 2f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.2916767f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("legLeft",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 57.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.2916767f, AnimationHelper.createRotationalVector(0f, 0f, -50f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.375f, AnimationHelper.createRotationalVector(0f, 0f, -25f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 57.5f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("legRight",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.125f, AnimationHelper.createTranslationalVector(0f, 2f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.3433333f, AnimationHelper.createTranslationalVector(0f, 2f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.4167667f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("legRight",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 57.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.4167667f, AnimationHelper.createRotationalVector(0f, 0f, -50f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, -25f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 57.5f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("jaw",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 20f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.375f, AnimationHelper.createRotationalVector(0f, 0f, 5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 20f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("lowerBody",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.375f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("lowerBody",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 2.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.375f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 2.5f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("earRight",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -0.3f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.375f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, -0.3f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("earRight",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 10f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.375f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0.5f, 10f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("earLeft",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -0.3f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.375f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, -0.3f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("earLeft",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 10f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.375f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0.5f, 10f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("bodyFur",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, -3f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.375f, AnimationHelper.createRotationalVector(0f, 0f, 3f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, -3f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("Mane",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(7.5f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.375f, AnimationHelper.createRotationalVector(-7.5f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(7.5f, 0f, 0f),
									Transformation.Interpolations.LINEAR))).build();
	public static final Animation BITE = Animation.Builder.create(1f).looping()
			.addBoneAnimation(EntityModelPartNames.HEAD,
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, -15f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, -15f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("jaw",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, -20f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, 0f, 40f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, -20f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, -20f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("earRight",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, -20f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("earLeft",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 20f, 0f),
									Transformation.Interpolations.LINEAR))).build();
}
