package net.jukoz.me.entity.beasts.warg;

import net.minecraft.client.render.entity.animation.Animation;
import net.minecraft.client.render.entity.animation.AnimationHelper;
import net.minecraft.client.render.entity.animation.Keyframe;
import net.minecraft.client.render.entity.animation.Transformation;
import net.minecraft.client.render.entity.model.EntityModelPartNames;

public class WargAnimations {
	public static final Animation SITTING_DOWN = Animation.Builder.create(2.25f)
.addBoneAnimation("root",
						  new Transformation(Transformation.Targets.TRANSLATE,
		new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("warg",
									  new Transformation(Transformation.Targets.TRANSLATE,
		new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, -8f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("warg",
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, -22.5f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation(EntityModelPartNames.HEAD,
									  new Transformation(Transformation.Targets.TRANSLATE,
		new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 4f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation(EntityModelPartNames.HEAD,
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 12.5f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armLeft",
									  new Transformation(Transformation.Targets.TRANSLATE,
		new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 4f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armLeft",
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 22.5f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armRight",
									  new Transformation(Transformation.Targets.TRANSLATE,
		new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 4f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armRight",
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 22.5f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("legRight",
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createRotationalVector(-17.5f, 0f, -65f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("legLeft",
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createRotationalVector(17.5f, 0f, -65f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("tail",
									  new Transformation(Transformation.Targets.TRANSLATE,
		new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, -3f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("tail",
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createRotationalVector(2.88f, -29.87f, 79.23f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("jaw",
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("earLeft",
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 32.5f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("earRight",
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(0f, -32.5f, 0f),
	Transformation.Interpolations.LINEAR))).build();
	public static final Animation STANDING_UP = Animation.Builder.create(1.4167667f)
.addBoneAnimation("root",
						  new Transformation(Transformation.Targets.TRANSLATE,
		new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("warg",
									  new Transformation(Transformation.Targets.TRANSLATE,
		new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -8f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("warg",
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, -22.5f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation(EntityModelPartNames.HEAD,
									  new Transformation(Transformation.Targets.TRANSLATE,
		new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 4f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation(EntityModelPartNames.HEAD,
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 12.5f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armLeft",
									  new Transformation(Transformation.Targets.TRANSLATE,
		new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 4f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armLeft",
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 22.5f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armRight",
									  new Transformation(Transformation.Targets.TRANSLATE,
		new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 4f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armRight",
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 22.5f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("legRight",
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(-17.5f, 0f, -65f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("legLeft",
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(17.5f, 0f, -65f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("tail",
									  new Transformation(Transformation.Targets.TRANSLATE,
		new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -3f, 0f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("tail",
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0f, AnimationHelper.createRotationalVector(2.88f, -29.87f, 79.23f),
	Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("jaw",
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("earLeft",
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 32.5f, 0f),
	Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("earRight",
									  new Transformation(Transformation.Targets.ROTATE,
		new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, -32.5f, 0f),
	Transformation.Interpolations.LINEAR))).build();
	public static final Animation SITTING = Animation.Builder.create(0f).looping()
			.addBoneAnimation("root",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("warg",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -8f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("warg",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, -22.5f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation(EntityModelPartNames.HEAD,
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 4f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation(EntityModelPartNames.HEAD,
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 12.5f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armLeft",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 4f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armLeft",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 22.5f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armRight",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 4f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armRight",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 22.5f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("legRight",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(-17.5f, 0f, -65f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("legLeft",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(17.5f, 0f, -65f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("tail",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -3f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("tail",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(2.88f, -29.87f, 79.23f),
									Transformation.Interpolations.LINEAR))).build();
	public static final Animation GROOM = Animation.Builder.create(3.5416765f)
			.addBoneAnimation("root",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("warg",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -8f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("warg",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, -22.5f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation(EntityModelPartNames.HEAD,
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 4f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation(EntityModelPartNames.HEAD,
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 12.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.5f, AnimationHelper.createRotationalVector(-35f, -22.5f, 42.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(-36.33f, -26.56f, 45.7f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armLeft",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 4f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armLeft",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 22.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.5f, AnimationHelper.createRotationalVector(47.26f, -58.32f, -90.64f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armRight",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 4f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armRight",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 22.5f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("legRight",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(-17.5f, 0f, -65f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("legLeft",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(17.5f, 0f, -65f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("tail",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -3f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("tail",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(3.04f, -34.87f, 78.93f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(4.63f, -57.32f, 76.77f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("jaw",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 20f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.9583434f, AnimationHelper.createRotationalVector(0f, 0f, 5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.1676667f, AnimationHelper.createRotationalVector(0f, 0f, 20f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.375f, AnimationHelper.createRotationalVector(0f, 0f, 5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.5834333f, AnimationHelper.createRotationalVector(0f, 0f, 20f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.8343333f, AnimationHelper.createRotationalVector(0f, 0f, 5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2.0416765f, AnimationHelper.createRotationalVector(0f, 0f, 20f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2.25f, AnimationHelper.createRotationalVector(0f, 0f, 5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2.4583435f, AnimationHelper.createRotationalVector(0f, 0f, 20f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("earLeft",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.5f, AnimationHelper.createRotationalVector(-30f, 30f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("earRight",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.5f, AnimationHelper.createRotationalVector(30f, -30f, 0f),
									Transformation.Interpolations.LINEAR))).build();
	public static final Animation LAYING = Animation.Builder.create(0f).looping()
			.addBoneAnimation("root",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("warg",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -8f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("warg",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, -22.5f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation(EntityModelPartNames.BODY,
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -3f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation(EntityModelPartNames.BODY,
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 22.5f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation(EntityModelPartNames.HEAD,
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(-3f, -10f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation(EntityModelPartNames.HEAD,
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 12.5f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armLeft",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(-4f, -6f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armLeft",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(17.44f, -1.5f, -62.73f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armRight",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(-4f, -6f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armRight",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(-24.94f, 1.5f, -62.73f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("legRight",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(-17.5f, 0f, -65f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("legLeft",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(17.5f, 0f, -65f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("tail",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -3f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("tail",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(2.88f, -29.87f, 79.23f),
									Transformation.Interpolations.LINEAR))).build();
	public static final Animation LAYINGGROOM = Animation.Builder.create(3.1676665f)
			.addBoneAnimation("root",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("warg",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -8f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("warg",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, -22.5f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation(EntityModelPartNames.BODY,
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -3f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation(EntityModelPartNames.BODY,
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 22.5f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation(EntityModelPartNames.HEAD,
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(-3f, -10f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(1f, -4f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation(EntityModelPartNames.HEAD,
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 12.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(14.13f, 36.91f, 43.57f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.0416767f, AnimationHelper.createRotationalVector(43.67f, 35.19f, 47.42f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armLeft",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(-4f, -6f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("armLeft",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(17.44f, -1.5f, -62.73f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("armRight",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(-4f, -6f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(-1f, -8f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armRight",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(-24.94f, 1.5f, -62.73f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(-120.73f, 59.33f, -186.54f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("legRight",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(-17.5f, 0f, -65f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("legLeft",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(17.5f, 0f, -65f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("tail",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -3f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("tail",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(2.88f, -29.87f, 79.23f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("jaw",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.0416767f, AnimationHelper.createRotationalVector(0f, 0f, 20f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.2916767f, AnimationHelper.createRotationalVector(0f, 0f, 12.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.5416767f, AnimationHelper.createRotationalVector(0f, 0f, 20f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.7916767f, AnimationHelper.createRotationalVector(0f, 0f, 12.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 20f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2.25f, AnimationHelper.createRotationalVector(0f, 0f, 12.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2.5f, AnimationHelper.createRotationalVector(0f, 0f, 20f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2.75f, AnimationHelper.createRotationalVector(0f, 0f, 12.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(3f, AnimationHelper.createRotationalVector(0f, 0f, 20f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("earLeft",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 47.5f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("earRight",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, -47.5f, 0f),
									Transformation.Interpolations.LINEAR))).build();
	public static final Animation WALK = Animation.Builder.create(2f).looping()
			.addBoneAnimation("root",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation(EntityModelPartNames.BODY,
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation(EntityModelPartNames.BODY,
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1f, AnimationHelper.createRotationalVector(5f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(2f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation(EntityModelPartNames.HEAD,
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.4583433f, AnimationHelper.createTranslationalVector(0f, 0.5f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, 0.5f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation(EntityModelPartNames.HEAD,
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, -7.5f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("armLeft",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 1f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.3433333f, AnimationHelper.createTranslationalVector(0f, -0.25f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.625f, AnimationHelper.createTranslationalVector(-2f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 1f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.4583433f, AnimationHelper.createTranslationalVector(0f, 2.42f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 1f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("armLeft",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, -35f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.3433333f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.625f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 25f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, -35f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("armRight",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0.83f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.4583433f, AnimationHelper.createTranslationalVector(0f, 2.83f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0.83f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.3433333f, AnimationHelper.createTranslationalVector(0f, -0.25f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.5834333f, AnimationHelper.createTranslationalVector(-2f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0.83f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("armRight",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 35f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, -35f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.3433333f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.5834333f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 35f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("legRight",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.3433333f, AnimationHelper.createTranslationalVector(0f, 0.67f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.625f, AnimationHelper.createTranslationalVector(-2f, 0.84f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.4583433f, AnimationHelper.createTranslationalVector(0f, 3f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("legRight",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, -45f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.3433333f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.625f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 35f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, -45f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("legLeft",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.4583433f, AnimationHelper.createTranslationalVector(0f, 3f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.3433333f, AnimationHelper.createTranslationalVector(0f, 0.67f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.5834333f, AnimationHelper.createTranslationalVector(-2f, 0.84f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("legLeft",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 35f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, -35f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.3433333f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.5834333f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 35f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("bodyFur",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(8.5f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1f, AnimationHelper.createRotationalVector(-8.5f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(2f, AnimationHelper.createRotationalVector(8.5f, 0f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("tail",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("tail",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 17.5f, 32.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1f, AnimationHelper.createRotationalVector(0f, -17.5f, 32.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 17.5f, 32.5f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("jaw",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("earLeft",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 50f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("earRight",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, -50f, 0f),
									Transformation.Interpolations.CUBIC))).build();
	public static final Animation RUN = Animation.Builder.create(0.75f).looping()
			.addBoneAnimation("warg",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 1f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.375f, AnimationHelper.createTranslationalVector(0f, -2f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 1f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("warg",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, -7.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.375f, AnimationHelper.createRotationalVector(0f, 0f, 5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, -7.5f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation(EntityModelPartNames.BODY,
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.375f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation(EntityModelPartNames.BODY,
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 2.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.375f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 2.5f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation(EntityModelPartNames.HEAD,
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, -12.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.125f, AnimationHelper.createRotationalVector(0f, 0f, -12.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, -12.5f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("armLeft",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.25f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.5834334f, AnimationHelper.createTranslationalVector(0f, 3f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("armLeft",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, -60f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, 0f, 27.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, -60f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("armRight",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.4583433f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.6766666f, AnimationHelper.createTranslationalVector(0f, 3f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("armRight",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, -60f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.375f, AnimationHelper.createRotationalVector(0f, 0f, 25.36f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.4583433f, AnimationHelper.createRotationalVector(0f, 0f, 30f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, -60f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("legRight",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.125f, AnimationHelper.createTranslationalVector(0f, 2f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.3433333f, AnimationHelper.createTranslationalVector(0f, 2f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.4167667f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("legRight",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 57.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.4167667f, AnimationHelper.createRotationalVector(0f, 0f, -50f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, -25f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 57.5f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("legLeft",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.08343333f, AnimationHelper.createTranslationalVector(0f, 2f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.20834334f, AnimationHelper.createTranslationalVector(0f, 2f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.2916767f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("legLeft",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 57.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.2916767f, AnimationHelper.createRotationalVector(0f, 0f, -50f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.375f, AnimationHelper.createRotationalVector(0f, 0f, -25f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 57.5f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("mane",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(7.5f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.375f, AnimationHelper.createRotationalVector(-7.5f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(7.5f, 0f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("bodyFur",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, -3f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.375f, AnimationHelper.createRotationalVector(0f, 0f, 3f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, -3f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("tail",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(-0.42f, -0.41f, 122.43f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.3433333f, AnimationHelper.createRotationalVector(0.31f, -0.5f, 44.93f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(-0.42f, -0.41f, 122.43f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("jaw",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 17.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.375f, AnimationHelper.createRotationalVector(0f, 0f, 5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 17.5f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("earLeft",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -0.3f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.375f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, -0.3f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("earLeft",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 10f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.375f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0.5f, 10f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("earRight",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -0.3f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.375f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, -0.3f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("earRight",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 10f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.375f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0.5f, 10f),
									Transformation.Interpolations.CUBIC))).build();
	public static final Animation BITE = Animation.Builder.create(0.5f).looping().build();
	public static final Animation STRETCH = Animation.Builder.create(2.9167665f)
			.addBoneAnimation(EntityModelPartNames.BODY,
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, -3f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, -3f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation(EntityModelPartNames.BODY,
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 20f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.5f, AnimationHelper.createRotationalVector(0f, 0f, 25f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation(EntityModelPartNames.HEAD,
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, -6f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, -7f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation(EntityModelPartNames.HEAD,
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, -17.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.5f, AnimationHelper.createRotationalVector(0f, 0f, -17.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2.25f, AnimationHelper.createRotationalVector(-22.5f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armLeft",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, -3f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.5f, AnimationHelper.createTranslationalVector(1f, -4f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armLeft",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, -42.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.5f, AnimationHelper.createRotationalVector(0f, 0f, -42.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armRight",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, -3f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.5f, AnimationHelper.createTranslationalVector(1f, -4f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("armRight",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, -42.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.5f, AnimationHelper.createRotationalVector(0f, 0f, -42.5f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("bodyFur",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2.25f, AnimationHelper.createRotationalVector(-17.5f, 0f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("jaw",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 35f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.5f, AnimationHelper.createRotationalVector(0f, 0f, 35f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR))).build();
}
