dependencies {
    implementation project(':sevenstars-api')
    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.4'
    testImplementation 'org.ow2.asm:asm:9.7.1'
}

tasks.named('test') {
    dependsOn tasks.named('runData')
    useJUnitPlatform()
}

tasks.named('jar') {
    dependsOn tasks.named('runData')
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from('src/main/generated')
}
