mod_id=sevenstars_api
mod_name=Seven Stars API
mod_license=ARR
mod_version=1.0.1-1.21.1-beta
maven_group=net.sevenstars.api
archives_base_name=SevenStarsAPI
mod_authors=Jukoz, ObliviousCrab, TomSchlom, Boenndal, Jooble, Sindavar, Angmarzku, Scosher, Osserc, Kolhosp, CoffeeViking, Nautilus, Arwaeneth, Thud, Akkon, Louise
mod_description=Shared API for the Seven Stars Middle-earth modules.
